# Deployment Docker Compose Configuration
# This file should be manually placed on the production server at /home/$USER/web/docker-compose.deploy.yml
# It references the pre-built image from GitHub Container Registry - NO building happens here

services:
  app:
    image: ghcr.io/jaeminkim/mysite:latest
    pull_policy: always  # Always pull the latest image on restart
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/prod.db
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data:rw
      # Optional: Mount uploads if you have user-uploaded images
      - ./public/images:/app/public/images:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
